on: 
  workflow_dispatch:

name: Bulk issue creator

jobs:
  bulk_issue_creator:
    runs-on: ubuntu-latest
    name: Bulk Issue Creator
    steps:
      - name: Checkout template and data
        uses: actions/checkout@v2
      - name: Create bulk issues
        uses: benbalter/bulk-issue-creator@main
        with: 
          write: 'true'
